config/routes.rb
Rails.application.routes.draw do
  get 'hello_world', to: 'hello_world#index'
  root "characters#index"

  resources :characters
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
  # dropdown selections
  RACES = %w(Dragonborn Dwarf Elf Gnome Half-Elf Half-Orc Halfling Human Tiefling)
  CLASSES = %w(Barbarian Bard Cleric Druid Fighter Monk Paladin Ranger Rogue Sorcerer Warlock Wizard)
  BACKGROUNDS = %w(Charlatan Criminal
Entertainer Folk Hero Guild Artisan Hermit Noble Outlander Sage Sailor Soldier Urchin)
  ALIGNMENTS = %w(Lawful-Good Neutral-Good Chaotic-Good
                  Lawful-Neutral True-Neutral Chaotic-Neutral
                  Lawful-Evil Neutral-Evil Chaotic-Evil)

  validates :player_name, presence: true
  validates :name, presence: true, uniqueness: true
  validates :eyes, presence: true
  validates :hair, presence: true
  validates :skin, presence: true
  validates :weight, numericality: { only_integer: true, greater_than: 0 }
  validates :age, numericality: { only_integer: true, greater_than: 0 }
  validates :backstory, length: { minimum: 50 }

  # fields with dropdowns
  validates :race, inclusion: { in: RACES }
  validates :character_class, inclusion: { in: CLASSES }
  validates :background, inclusion: { in: BACKGROUNDS }
  validates :alignment, inclusion: { in: ALIGNMENTS }

  # serializer

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController

  def index
    @characters = Character.all
  end

  def new
    @character = Character.new
  end

  def create
    @character = Character.new(character_params)
    if @character.save
      redirect_to @character
    else
      render :new
    end
  end

  def show
    @character = Character.find(params[:id])
  end

  def edit
    @character = Character.find(params[:id])
  end

  def update
    @character = Character.find(params[:id])
    @character.update(character_params)
    if @character.update(character_params)
      redirect_to @character
    else
      render :edit
    end
  end

  def destroy
    @character = Character.find(params[:id])
    @character.destroy
    redirect_to characters_path
  end

end

private

def character_params
  params.require(:character).permit(:player_name, :name, :character_class, :race, :eyes, :skin, :hair,
              :background, :alignment, :ideals, :bonds, :flaws, :personality_traits, :backstory, :weight,
              :age)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/_basic_info.html.erb
<%= form_with(model: @character, local: true) do |f| %>
  <%= render "errors", object: @character %>

  <%= f.label :player_name %>
  <%= f.text_field :player_name, autofocus: true %>
  <br>
  <h3>Physical Traits</h3>
  <br>
  <%= f.label :race %>
  <%= f.select :race, Character::RACES %>
  <br>
  <%= f.label :eyes %>
  <%= f.text_field :eyes %>
  <br>
  <%= f.label :hair %>
  <%= f.text_field :hair %>
  <br>
  <%= f.label :skin %>
  <%= f.text_field :skin %>
  <br>
  <h3>Character Traits</h3>
  <br>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :character_class %>
  <%= f.select :character_class, Character::CLASSES %>
  <br>
  <%= f.label :background %>
  <%= f.select :background, Character::BACKGROUNDS %>
  <br>
  <%= f.label :alignment %>
  <%= f.select :alignment, Character::ALIGNMENTS %>
  <br>
  <%= f.label :ideals %>
  <%= f.text_area :ideals, value: "The thing that drives your character"  %>
  <br>
  <%= f.label :bonds %>
  <%= f.text_area :bonds, value: "This represents your character's connection to people, places, and events"  %>
  <br>
  <%= f.label :flaws %>
  <%= f.text_area :flaws, value: "Your character's vice, compulsion, fear, or weakness"  %>
  <br>
  <%= f.label :personality_traits %>
  <%= f.text_area :personality_traits, value: "Choose 2 - these are small, simple ways to help you set your character apart from every other character"  %>
  <br>
  <%= f.label :backstory %>
  <%= f.text_area :backstory %>
  <br>
  <%= f.submit %>
<% end %>

app/views/characters/edit.html.erb
<h1>How might you adjust your champion?</h1>

<%= render "layouts/editable_basic_info", character: @character %>

app/views/characters/index.html.erb
<h1>All of our current Champions</h1>

<ul>
  <% @characters.each do |character| %>
    <li>
      <%= link_to character.name, character_path(character.id) %>
    </li>
  <% end %>
</ul>

app/views/characters/new.html.erb
<h1>Create a New Character</h1>

<%= render "layouts/all_fields", character: @character %>

app/views/characters/show.html.erb
<h1>
  <%= @character.player_name %>'s selected Champion:
</h1>

Name:
  <b><%= @character.name == nil ? "Seems your character has no name - go ahead and Edit to give them one" : @character.name %></b>
<br>
Level: <%= @character.level %>
<br>
Experience: <%= @character.experience_points %>
<br>
Race: <%= @character.race %>
<br>
Class: <%= @character.character_class %>
<br>
<h3>Physical Description:</h3>
<p>
Age: <%= @character.age %>
<br>
Weight: <%= @character.weight %>
<br>
Eyes: <%= @character.eyes %>
<br>
Hair: <%= @character.hair %>
<br>
Skin: <%= @character.skin %>
</p>
<h3>Character Description</h3>
<p>
Alignment: <%= @character.alignment %>
<br>
Background: <%= @character.background %>
<br>
Backstory: <%= @character.backstory %>
</p>
<br>

<br>
<%= link_to "Edit the character", edit_character_path %>
<br>
<br>
<%= link_to "REMOVE THE CHARACTER FROM THIS PLANE OF EXISTENCE", character_path, method: :delete,
                data: { confirm: 'Are you sure?' } %>

app/views/hello_world/index.html.erb
<h1>Hello World</h1>
<%= react_component("HelloWorld", props: @hello_world_props, prerender: false) %>

app/views/layouts/_all_fields.html.erb
<%= form_with(model: @character, local: true) do |f| %>
  <%= render "layouts/errors", object: @character %>

  <h3>What is your name Player?</h3>
  <%= f.label :player_name %>
  <%= f.text_field :player_name, autofocus: true %>
  <br>
  <h3>What is the name of your Champion?</h3>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <h3>And who is your champion?</h3>
  <p>Every character belongs to a race, one of the many intelligent humanoid species in the D&D world.</p>
  <p>The race you choose contributes to your character's identity in an important way, by establishing
    a general appearance and the natural talents gained form culture and ancestry.</p>
  <p><b>Please refer to page 17 of the Player's Handbook (PHB) or D&D Beyond's <%= link_to 'list' , 'https://www.dndbeyond.com/classes', target: 'blank' %>
    to see the full list of races and their traits</b></p>
  <%= f.label :race %>
  <%= f.select :race, Character::RACES %>
  <br>
  <h3>What does your champion do?</h3>
  <p>Class is the primary definition of what your character can do. It's more than a profession; it's your character's
    calling.</p>
  <p>Your class gives you a variety of special features, such as a fighter's mastery of weapons and armor, and a
    wizard's spells.</p>
  <p><b>Please refer to page 45 of the PHB or D&D Beyond's <%= link_to 'list' , 'https://www.dndbeyond.com/races', target: 'blank' %>
    to see the full table of classes and their features</b></p>
  <%= f.label :character_class %>
  <%= f.select :character_class, Character::CLASSES %>
  <br>
  <h2>Time to flush out your Champion</h2>
  <h3>Physical Traits</h3>
  <br>
  <%= f.label :eyes %>
  <%= f.text_field :eyes %>
  <br>
  <%= f.label :hair %>
  <%= f.text_field :hair %>
  <br>
  <%= f.label :skin %>
  <%= f.text_field :skin %>
  <br>
  <%= f.label :weight %>
  <%= f.number_field :weight %>
  <br>
  <%= f.label :age %>
  <%= f.number_field :age %>
  <br>
  <h3>Character Traits</h3>
  <br>
  <%= f.label :background %>
  <%= f.select :background, Character::BACKGROUNDS %>
  <br>
  <%= f.label :alignment %>
  <%= f.select :alignment, Character::ALIGNMENTS %>
  <br>
  <%= f.label :ideals %>
  <%= f.text_area :ideals, value: "The thing that drives your character"  %>
  <br>
  <%= f.label :bonds %>
  <%= f.text_area :bonds, value: "This represents your character's connection to people, places, and events"  %>
  <br>
  <%= f.label :flaws %>
  <%= f.text_area :flaws, value: "Your character's vice, compulsion, fear, or weakness"  %>
  <br>
  <%= f.label :personality_traits %>
  <%= f.text_area :personality_traits, value: "Choose 2 - these are small, simple ways to help you set your character apart from every other character"  %>
  <br>
  <%= f.label :backstory %>
  <%= f.text_area :backstory %>
  <br>
  <%= f.submit %>
<% end %>

app/views/layouts/_basic_info.html.erb
<%= form_with(model: @character, local: true) do |f| %>
  <%= render "layouts/errors", object: @character %>

  <h3>What is your name Player?</h3>
  <%= f.label :player_name %>
  <%= f.text_field :player_name, autofocus: true %>
  <br>
  <h3>What is the name of your Champion?</h3>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <h3>And who is your champion?</h3>
  <p>Every character belongs to a race, one of the many intelligent humanoid species in the D&D world.</p>
  <p>The race you choose contributes to your character's identity in an important way, by establishing
  a general appearance and the natural talents gained form culture and ancestry.</p>
  <p><b>Please refer to page 17 of the Player's Handbook (PHB) to see the full list of races and their traits</b></p>
  <%= f.label :race %>
  <%= f.select :race, Character::RACES %>
  <br>
  <h3>What does your champion do?</h3>
  <p>Class is the primary definition of what your character can do. It's more than a profession; it's your character's
  calling.</p>
  <p>Your class gives you a variety of special features, such as a fighter's mastery of weapons and armor, and a
  wizard's spells.</p>
  <p><b>Please refer to page 45 of the PHB to see the full table of classes and their features</b></p>
  <%= f.label :character_class %>
  <%= f.select :character_class, Character::CLASSES %>
  <br>
  <br>
  <%= f.submit %>
<% end %>

app/views/layouts/_character_description.html.erb
<%= form_with(model: @character, local: true) do |f| %>
  <%= render "errors", object: @character %>
  <h2>Time to flush out your Champion</h2>
  <h3>Physical Traits</h3>
  <br>
  <%= f.label :eyes %>
  <%= f.text_field :eyes %>
  <br>
  <%= f.label :hair %>
  <%= f.text_field :hair %>
  <br>
  <%= f.label :skin %>
  <%= f.text_field :skin %>
  <br>

  <%= f.label :background %>
  <%= f.select :background, Character::BACKGROUNDS %>


  <h3>Character Traits</h3>
  <br>
  <%= f.label :alignment %>
  <%= f.select :alignment, Character::ALIGNMENTS %>
  <br>
  <%= f.label :ideals %>
  <%= f.text_area :ideals, value: "The thing that drives your character"  %>
  <br>
  <%= f.label :bonds %>
  <%= f.text_area :bonds, value: "This represents your character's connection to people, places, and events"  %>
  <br>
  <%= f.label :flaws %>
  <%= f.text_area :flaws, value: "Your character's vice, compulsion, fear, or weakness"  %>
  <br>
  <%= f.label :personality_traits %>
  <%= f.text_area :personality_traits, value: "Choose 2 - these are small, simple ways to help you set your character apart from every other character"  %>
  <br>
  <%= f.label :backstory %>
  <%= f.text_area :backstory %>
  <br>
  <%= f.submit %>
<% end %>

app/views/layouts/_editable_basic_info.html.erb
<%= form_with(model: @character, local: true) do |f| %>
  <%= render "errors", object: @character %>

  <%= f.label :player_name %>
  <%= f.text_field :player_name, autofocus: true %>
  <br>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :backstory %>
  <%= f.text_area :backstory %>
  <br>
  <%= f.submit %>
<% end %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div class="errors">
    <h2>
      Oops! Your form could not be saved.
    </h2>
    <h3>
      Please correct the following
      <%= pluralize(object.errors.size, "error") %>:
    </h3>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<h2 >Welcome to all that dare...</h2>
<h2 >Fate awaits those champions that choose to participate</h2>
<%= link_to "Character List", characters_path %>
|
<%= link_to 'Create a new character...if you dare', new_character_path %>

<hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>D&D</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "layouts/header" %>
    <%= yield %>
  </body>
</html>

app/views/layouts/hello_world.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReactOnRailsWithWebpacker</title>
    <%= csrf_meta_tags %>
    <%= javascript_pack_tag 'hello-world-bundle' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>